print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Vault/Desktop/JQVerticalSlice/Assets/Art Assets/World Object/dumpster (1).mb"`)
{		
	file -o "/Users/Vault/Desktop/JQVerticalSlice/Assets/Art Assets/World Object/dumpster (1).mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Vault/Desktop/JQVerticalSlice/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Vault/Desktop/JQVerticalSlice/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Vault/Desktop/JQVerticalSlice/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
